name: DUCO CLI Miner

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # chạy mỗi 6 tiếng (UTC)

jobs:
  cli-mine:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # tối đa 6 tiếng

    steps:
    - name: Clone repo
      run: git clone https://github.com/Tudz1011-pp/minercli.git miner

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install CLI-only dependencies
      run: |
        cd miner
        npm install benchmark@2.1.4
        npm install ini@3.0.0
        npm install js-sha1@0.6.0
        npm install jshashes@1.0.8
        npm install node-fetch@2.6.1
        npm install promise-socket@6.0.3
        npm install rusha@0.8.14
        npm install sha1@1.1.1

    - name: Run DUCO CLI miner
      run: |
        cd miner
        node cli.js
